name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.84ee7fa6-4b83-4630-8876-516352712995}}
          heroku_app_name: "devopswpf" #Must be unique in Heroku
          heroku_email: "r0841635@student.thomasmore.be"